import { markTitleDraft } from "../slack/confirm/draft.js";
import { normalizeWorkflowSource, stripExplicitTemplatePrefix } from "../forge/source-text.js";
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { getDataRoot } from "../config.js";
import { assertSafeId } from "../security/paths.js";
import {
  generateTemplateScaffold,
  listCustomTemplates,
  registerCustomTemplate,
  validateTemplatePackage,
} from "./custom.js";
import { getTemplate, getTemplateSample } from "./registry.js";
import {
  docforgeCompileDocument,
  docforgeCreateDocument,
  docforgeExportDocument,
} from "../service.js";

export { listCustomTemplates };

export type ScaffoldField = {
  name: string;
  type: string;
  required?: boolean;
  description?: string;
};

export type StudioResult = {
  success: boolean;
  template_id?: string;
  output_path?: string;
  errors?: string[];
  proof?: {
    document_id: string;
    page_count?: number;
    pdf_basename: string;
  };
};

/**
 * Parse `@forge template scaffold acme_brief --name "Acme Brief" --fields title,summary,body`
 */
export function parseScaffoldCommand(text: string): {
  template_id: string;
  name: string;
  description: string;
  fields: ScaffoldField[];
} | undefined {
  const match = text.match(
    /\btemplate\s+scaffold\s+([a-z][a-z0-9_-]*)\b/i,
  );
  if (!match?.[1]) return undefined;

  const template_id = match[1].toLowerCase();
  const nameMatch = text.match(/--name\s+"([^"]+)"/i) ?? text.match(/--name\s+(\S+)/i);
  const fieldsMatch = text.match(/--fields\s+([a-z0-9_,\s-]+)/i);

  const name = nameMatch?.[1]?.trim() ?? template_id.replace(/_/g, " ");
  const fieldNames = (fieldsMatch?.[1] ?? "summary,body")
    .split(/[,\s]+/)
    .map((f) => f.trim())
    .filter(Boolean);

  const fields: ScaffoldField[] = fieldNames.map((field) => ({
    name: field,
    type: "string",
    required: field === "summary",
    description: field.replace(/_/g, " "),
  }));

  return {
    template_id,
    name,
    description: `Custom ${name} template generated by Forge Template Studio`,
    fields,
  };
}

/** Parse `draft using my_template` / `draft with template my_template`. */
export function parseExplicitTemplateId(text: string): string | undefined {
  const match = text.match(/\b(?:using|with\s+template)\s+([a-z][a-z0-9_-]*)\b/i);
  return match?.[1]?.toLowerCase();
}

/**
 * Scaffold → validate → register → compile sample.json as proof the package works.
 */
export async function scaffoldRegisterAndProve(input: {
  template_id: string;
  name: string;
  description: string;
  fields: ScaffoldField[];
}): Promise<StudioResult> {
  try {
    assertSafeId(input.template_id, "template_id");
  } catch (err) {
    return {
      success: false,
      errors: [err instanceof Error ? err.message : String(err)],
    };
  }

  const staging = path.join(getDataRoot(), "template-scaffold", input.template_id);
  await rm(staging, { recursive: true, force: true });
  await mkdir(staging, { recursive: true });

  const scaffold = generateTemplateScaffold(input);
  for (const [file, content] of Object.entries(scaffold.files)) {
    await writeFile(path.join(staging, file), content, "utf8");
  }

  const validation = await validateTemplatePackage(staging);
  if (!validation.ok) {
    return { success: false, output_path: staging, errors: validation.errors };
  }

  const registered = await registerCustomTemplate({
    template_id: input.template_id,
    source_path: staging,
  });
  if (!registered.ok) {
    return { success: false, output_path: staging, errors: registered.errors };
  }

  const sample = (await getTemplateSample(input.template_id)) as Record<string, unknown>;
  const created = await docforgeCreateDocument({
    template_id: input.template_id,
    data: sample,
  });
  if (created.status !== "created" || !created.document_id) {
    return {
      success: false,
      template_id: input.template_id,
      errors: [created.diagnostic?.message ?? "Proof compile create failed"],
    };
  }

  const compiled = await docforgeCompileDocument(created.document_id);
  if (!compiled.success) {
    return {
      success: false,
      template_id: input.template_id,
      errors: [compiled.diagnostics?.[0]?.message ?? "Proof compile failed"],
    };
  }

  const exported = await docforgeExportDocument({
    document_id: created.document_id,
    formats: ["pdf"],
  });
  if (!exported.success) {
    return {
      success: false,
      template_id: input.template_id,
      errors: [exported.diagnostic?.message ?? "Proof export failed"],
    };
  }

  return {
    success: true,
    template_id: input.template_id,
    output_path: staging,
    proof: {
      document_id: created.document_id,
      page_count: compiled.page_count,
      pdf_basename: exported.exports?.pdf ?? "output.pdf",
    },
  };
}

export async function buildDraftFromCustomTemplate(
  templateId: string,
  sourceText: string,
): Promise<{
  templateId: string;
  templateLabel: string;
  draftData: Record<string, unknown>;
  filename: string;
}> {
  const { meta } = await getTemplate(templateId);
  const sample = (await getTemplateSample(templateId)) as Record<string, unknown>;
  const cleaned = normalizeWorkflowSource(sourceText, { explicitTemplateId: templateId });
  const lines = cleaned.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
  const titleLine =
    lines.find((l) => !/^#+\s*$/.test(l) && l.length > 2)?.replace(/^#+\s*/, "") ?? meta.name;
  const title = titleLine.slice(0, 100);

  const draftData: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(sample)) {
    if (key === "title") continue;
    if (typeof value === "string" && /^Sample /i.test(value)) continue;
    draftData[key] = value;
  }
  draftData.title = title;
  if ("summary" in sample) draftData.summary = cleaned.slice(0, 4000) || title;
  if ("body" in sample) draftData.body = cleaned.slice(0, 8000) || cleaned;
  if ("body_md" in sample) draftData.body_md = cleaned.slice(0, 8000) || cleaned;
  if ("executive_summary" in sample) {
    draftData.executive_summary = cleaned.slice(0, 2000) || title;
  }

  const slug = title.replace(/[^A-Za-z0-9]+/g, "-").replace(/^-|-$/g, "") || meta.id;
  return {
    templateId,
    templateLabel: meta.name,
    draftData: markTitleDraft(draftData),
    filename: `${slug}.pdf`,
  };
}

export { stripExplicitTemplatePrefix };
