import type { BrandKit } from "./types.js";

export function compileBrandThemeTyp(kit: BrandKit, hasLogoInWorkspace: boolean): string {
  const lines = [
    "// Generated by DocForge brand compiler — do not edit",
    `#let brand-primary = rgb("${kit.colors.primary}")`,
    `#let brand-accent = rgb("${kit.colors.accent}")`,
    `#let brand-muted = rgb("${kit.colors.muted}")`,
    `#let brand-background = rgb("${kit.colors.background}")`,
    `#let brand-text = rgb("${kit.colors.text}")`,
    `#let brand-footer = "${kit.footer.replace(/"/g, '\\"')}"`,
    `#let body-font = "${kit.fonts.body}"`,
    `#let heading-font = "${kit.fonts.heading}"`,
  ];

  if (kit.logo && hasLogoInWorkspace) {
    lines.push(`#let brand-logo-path = "assets/${kit.logo}"`);
    lines.push(`#let brand-logo-alt = "${(kit.logo_alt ?? kit.name).replace(/"/g, '\\"')}"`);
    lines.push(`#let brand-logo = image(brand-logo-path, alt: brand-logo-alt)`);
  } else {
    lines.push("#let brand-logo = none");
    lines.push('#let brand-logo-alt = ""');
  }

  lines.push("");
  lines.push("#let brand-header-bar() = [");
  lines.push("  #if brand-logo != none [");
  lines.push("    #grid(");
  lines.push("      columns: (auto, 1fr),");
  lines.push("      gutter: 12pt,");
  lines.push("      align: (left + horizon, right + horizon),");
  lines.push("      box(width: 48pt)[#brand-logo],");
  lines.push("      align(right)[#text(size: 9pt, fill: brand-muted)[#brand-footer]]");
  lines.push("    )");
  lines.push("    #v(0.6em)");
  lines.push("    #line(length: 100%, stroke: 0.5pt + brand-accent)");
  lines.push("    #v(0.8em)");
  lines.push("  ]");
  lines.push("]");

  return lines.join("\n") + "\n";
}
