/** Strip default brand variable lines from template theme.typ before merging brand kit overrides. */
export function stripBrandDefaults(themeTyp: string): string {
  const skipPatterns = [
    /^#let brand-primary\s/,
    /^#let brand-accent\s/,
    /^#let brand-muted\s/,
    /^#let brand-background\s/,
    /^#let brand-text\s/,
    /^#let brand-footer\s/,
    /^#let body-font\s/,
    /^#let heading-font\s/,
    /^#let brand-logo\s/,
    /^#let brand-logo-alt\s/,
    /^#let brand-header-bar\(\)\s/,
    /^\/\/ Generated by DocForge brand compiler/,
  ];

  return themeTyp
    .split("\n")
    .filter((line) => !skipPatterns.some((p) => p.test(line.trim())))
    .join("\n")
    .trimStart();
}

export function mergeBrandTheme(brandBlock: string, templateThemeTyp: string): string {
  const remainder = stripBrandDefaults(templateThemeTyp);
  return `${brandBlock}\n${remainder}\n`;
}
